### ISSUE TITLE
Conditional deployments (from rootDir) will be marked as failure

### ISSUE THREAD

**Issue by jurrchen** [Bounceapp/render-action#213]
First off, thanks for building this! This is super useful.

I have a frontend and a backend service in a monorepo and with rootDir, these are only deployed when there are changes.

If there are no changes to a service, render-action gets stuck trying to find a deployment and then fail when it hits the x number of retries.

Any way to work around this? Like a way to say that if you don't find a deployment in x retries, mark as success?

**Comment by DReigada** [comment]
@jurrchen You should be able to configure the trigger of you workflow to only run when specific files are changed.

> Any way to work around this? Like a way to say that if you don't find a deployment in x retries, mark as success?

I don't see this being a correct solution for your problem, as it might hide some other failure during the deployment, eg: if Render doesn't trigger a deployment because of some misconfiguration.
